basePath: /
definitions:
  hospital-backend_internal_dto.LoginRequest:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  hospital-backend_internal_service.LoginResponse:
    properties:
      access_token:
        type: string
      user:
        $ref: '#/definitions/hospital-backend_internal_service.UserResponse'
    type: object
  hospital-backend_internal_service.UserResponse:
    properties:
      email:
        type: string
      first_name:
        type: string
      id:
        type: integer
      last_name:
        type: string
      role:
        type: string
    type: object
info:
  contact: {}
  description: Hospital Management System API
  title: Hospital Management API
  version: "1.0"
paths:
  /api/v1/auth/login:
    post:
      consumes:
      - application/json
      description: Authenticate user and return JWT access token
      parameters:
      - description: Login credentials
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/hospital-backend_internal_dto.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/hospital-backend_internal_service.LoginResponse'
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties: true
            type: object
      summary: User Login
      tags:
      - Authentication
swagger: "2.0"
